/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.AirportSys;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author User
 */
public class WelcomeFrame extends javax.swing.JFrame {

    ImageIcon sabiha=new ImageIcon(getClass().getResource("sabiha2.jpg"));
    ImageIcon ataturk=new ImageIcon(getClass().getResource("ataturk3.jpg"));
    ImageIcon esenboga=new ImageIcon(getClass().getResource("esenboga2.jpg"));
    ImageIcon welcome=new ImageIcon(getClass().getResource("banner.jpg"));
    AirportScreen as=new AirportScreen();
    
    public WelcomeFrame() {
        initComponents();
        setTitle("Welcome");
        banner.setIcon(welcome);
        setLocationRelativeTo(null);
        
    }

    public JComboBox<String> getCmbAirports() {
        return cmbAirports;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        cmbAirports = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        cmbAirports.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAirports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAirportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(cmbAirports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cmbAirports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAirportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAirportsActionPerformed
        // TODO add your handling code here:
        switch(cmbAirports.getSelectedItem().toString()){
            case "Sabiha":
                as.getAirport_img().setIcon(sabiha);
                as.getCmbParked().setModel(new DefaultComboBoxModel<String>(AirportSys.getFlight_IDs("Sabiha")));
                as.getTa_display().setText(AirportSys.display("Sabiha"));
                as.setAirport("Sabiha");
                break;
            case "Ataturk":
                as.getAirport_img().setIcon(ataturk);
                as.getCmbParked().setModel(new DefaultComboBoxModel<String>(AirportSys.getFlight_IDs("Ataturk")));
                as.getTa_display().setText(AirportSys.display("Ataturk"));
                as.setAirport("Ataturk");
                break;
            case "Esenboga":
                as.getAirport_img().setIcon(esenboga);
                as.getCmbParked().setModel(new DefaultComboBoxModel<String>(AirportSys.getFlight_IDs("Esenboga")));
                as.getTa_display().setText(AirportSys.display("Esenboga"));
                as.setAirport("Esenboga");
                break;
        }
        
        as.setVisible(true);
    }//GEN-LAST:event_cmbAirportsActionPerformed
    


    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println("denem");
    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(evt.getButton()== MouseEvent.BUTTON3)
            dispose();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JComboBox<String> cmbAirports;
    // End of variables declaration//GEN-END:variables
}
